
spring:
  application:
    name: "sathishconfigserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
server:
  port: 8888
