# Golden copy for the Configserver ver #3
spring:
  application:
    name: "sathishconfigserver"
  profiles:
    active: git
  #    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sathishjayapal/ideal-winner.git
          default-label: main
          timeout: 5
          clone-on-start: true
#        native:
#          search-locations: "classpath:/config"
server:
  port: 8888
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: configprops,env,health,info,logfile,loggers,metrics,prometheus
