# Golden copy for the Configserver ver #3
spring:
  application:
    name: "sathishconfigserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"
server:
  port: 8888
