# Golden copy for the Configserver ver #3
spring:
  application:
    name: "sathishconfigserver"

  profiles:
    active: git
  #    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sathishjayapal/ideal-winner.git
          default-label: main
          timeout: 5
          clone-on-start: true
          search-paths: '{application}'
      label: main
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
#        native:
#          search-locations: "classpath:/config"
server:
  port: 8888
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

encrypt:
  key: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAK8GMsEw44Vw71MsofkIaS5PWKVP1A2yNCxoXNP31VEi4gCUt2ViRkan/c4/WXW7eAOP07Qh7Z287TfZFbgH2oNpVBakuTo5VdmpknZ3z89I4ah36l3+DwaY7JuSSVl0KzDs/xXesmJxBU8gxtNh9AzTvYxuR4bTGPZDMVJuBQ9nAgMBAAECgYAoxQbZnavCD7aP51uriNwHX5BEob3BmvswRPcqoRZdmgSPIhU+VpAMMWGbw4HxPMQOAFjOIwEYt0OCuNyoS5wIkJwYpu5skP5dZ02+TnzZ4LQpEIyLWZtK2BVK/PXTGmMh0zYBE4Ruvx4pwfb0A0nltzY5H5yCR72QMnZloR/T0QJBAPb5MDkobGB19rUezSxUAuCQeLEmdmH5BHD71jtS/EaPCKGkp4ifZ/SO5N8JibyN5MLZ/dDZ51GOWOY4LTn9hbsCQQC1a9DfBVvtJlgtg+aITZwV+rHLKlVP141RbOmoYWJwrubja4fmkQuqXJNfeei3LQ6XclvXHujq9LLCpvlo7cxFAkEAxusDlTXivHqmn1DUrhxoSNjz7LLu7JA1rI6aCSQYvvfbWt4Udez2PLqOyrmS74RVuT78uKeZMU32ek7K1odEmwJBALR8SXTGURjSD+FgGoW5qDHZkO2M9QiUafv6vU4NbDCsX/kaLj58SD25EchncNRjF+QlGicekhvFSt4J3ZC9Gn0CQQDVLHandZGEYx6M1jWzZU8VN/DVUuxrAy3a8kpjxWzCpHCPl2uPr4v4Up3bw8oZwrUG6A06mgV2+bZ4uxkSV7oZ
